/*
 * The new mechanics' icons and emblems, for the renderer.
 * Generated by `npm run brand:mechanics` from src/core/brand/mechanics.ts; do not edit.
 *
 *   mechanicIcon("crown")                         decorative 24-unit icon, currentColor
 *   mechanicIcon("crown", { label: "Crown" })     the same, announced to screen readers
 *   mechanicIcon("crown", { className: "nav-icon" })  sized by the rail's own CSS
 *   mechanicEmblem("crown")                       80-unit emblem for an empty state, currentColor
 *   APOGEE_MECHANICS.names.crown, .lines.crown    the name and the one line, as the brand kit has them
 *   <svg data-mechanic-icon="daily" class="nav-icon"></svg>   static markup (the rail's tabs),
 *                                                  filled in once the document is parsed
 *
 * Ids: shadow, flag, daily, link (challenge link), crown, draft, race (live race).
 */
(function () {
  "use strict";
  var ICON_ATTRS = "viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.65\" stroke-linecap=\"round\" stroke-linejoin=\"round\"";
  var BODIES = {
  "shadow": "<path d=\"M12 6A6.5 6.5 0 1 1 12 18A6.5 6.5 0 0 0 12 6Z\" fill=\"currentColor\" fill-opacity=\".45\" stroke=\"none\"/><circle cx=\"9.5\" cy=\"12\" r=\"6.5\"/>",
  "flag": "<path d=\"M7 21V3.5\"/><path d=\"M7 4.5h12l-3 4 3 4H7\"/><path d=\"M4.5 21h5\"/>",
  "daily": "<path d=\"M3 16.5h18M8 20h8\"/><path d=\"M7 16.5a5 5 0 0 1 10 0\"/><path d=\"M12 9V6M6.7 11.2 4.6 9.1M17.3 11.2l2.1-2.1\"/>",
  "link": "<rect x=\"2.5\" y=\"12\" width=\"12.5\" height=\"6.5\" rx=\"3.25\" transform=\"rotate(-45 8.75 15.25)\"/><rect x=\"9\" y=\"5.5\" width=\"12.5\" height=\"6.5\" rx=\"3.25\" transform=\"rotate(-45 15.25 8.75)\"/>",
  "crown": "<path d=\"M4.5 17 3 7.5l5 3.5 4-6 4 6 5-3.5L19.5 17Z\"/><path d=\"M5 20.5h14\"/>",
  "draft": "<rect x=\"2.5\" y=\"4.5\" width=\"8.5\" height=\"15\" rx=\"1.5\"/><rect x=\"13\" y=\"4.5\" width=\"8.5\" height=\"15\" rx=\"1.5\"/><path d=\"m4.6 12.3 1.9 1.9 3.1-3.9M15.2 16.5l4.1-9\"/>",
  "race": "<path d=\"M3 8h8M3 16h11M21.5 3.5v17\"/><path d=\"m13.5 5.8 2.2 2.2-2.2 2.2-2.2-2.2Z\" fill=\"currentColor\"/><path d=\"m16.5 13.8 2.2 2.2-2.2 2.2-2.2-2.2Z\" fill=\"currentColor\"/>"
};
  var EMBLEMS = {
  "shadow": "<circle cx=\"40\" cy=\"40\" r=\"35\" fill=\"currentColor\" fill-opacity=\".06\" stroke=\"currentColor\" stroke-width=\"1.4\"/><path d=\"M40 2.5v6M40 71.5v6M2.5 40h6M71.5 40h6\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M67.6 15.3l3.2 3.2-3.2 3.2-3.2-3.2Z\" fill=\"currentColor\"/><path d=\"M40 24.51A17 17 0 1 1 40 55.49A17 17 0 0 0 40 24.51Z\" fill=\"currentColor\" fill-opacity=\"0.1\"/><path d=\"M40 24.51A17 17 0 1 1 40 55.49\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M40 24.51A17 17 0 0 0 40 55.49\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-opacity=\".5\" stroke-dasharray=\"1.5 3\"/><path d=\"M33 23a17 17 0 1 0 0 34a17 17 0 1 0 0-34Z\" fill=\"currentColor\" fill-opacity=\"0.28\" stroke=\"currentColor\" stroke-width=\"1.4\" stroke-linejoin=\"round\"/>",
  "flag": "<circle cx=\"40\" cy=\"40\" r=\"35\" fill=\"currentColor\" fill-opacity=\".06\" stroke=\"currentColor\" stroke-width=\"1.4\"/><path d=\"M40 2.5v6M40 71.5v6M2.5 40h6M71.5 40h6\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M67.6 15.3l3.2 3.2-3.2 3.2-3.2-3.2Z\" fill=\"currentColor\"/><path d=\"M31 21h21l-5 7H31Z\" fill=\"currentColor\" fill-opacity=\"0.48\"/><path d=\"M31 28h16l5 7H31Z\" fill=\"currentColor\" fill-opacity=\"0.17\"/><path d=\"M31 21h21l-5 7 5 7H31\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M31 60V18\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M31 12.4l2.6 2.6-2.6 2.6-2.6-2.6Z\" fill=\"currentColor\"/><path d=\"M22 60h18\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M26 64h10\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-opacity=\".5\"/>",
  "daily": "<circle cx=\"40\" cy=\"40\" r=\"35\" fill=\"currentColor\" fill-opacity=\".06\" stroke=\"currentColor\" stroke-width=\"1.4\"/><path d=\"M40 2.5v6M40 71.5v6M2.5 40h6M71.5 40h6\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M67.6 15.3l3.2 3.2-3.2 3.2-3.2-3.2Z\" fill=\"currentColor\"/><path d=\"M28 45a12 12 0 0 1 24 0Z\" fill=\"currentColor\" fill-opacity=\"0.28\" stroke=\"currentColor\" stroke-width=\"1.4\" stroke-linejoin=\"round\"/><path d=\"M33 45a7 7 0 0 1 14 0Z\" fill=\"currentColor\" fill-opacity=\"0.48\"/><path d=\"M14 45h52\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M40 29v-6M28.7 33.7l-4.2-4.2M51.3 33.7l4.2-4.2\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M27 59.5l3.5-6 3.5 6Z\" fill=\"currentColor\"/><path d=\"M40 53.1l3.4 3.4-3.4 3.4-3.4-3.4Z\" fill=\"currentColor\"/><path d=\"M46 53.5h7l-3.5 6Z\" fill=\"currentColor\"/>",
  "link": "<circle cx=\"40\" cy=\"40\" r=\"35\" fill=\"currentColor\" fill-opacity=\".06\" stroke=\"currentColor\" stroke-width=\"1.4\"/><path d=\"M40 2.5v6M40 71.5v6M2.5 40h6M71.5 40h6\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M67.6 15.3l3.2 3.2-3.2 3.2-3.2-3.2Z\" fill=\"currentColor\"/><g transform=\"rotate(-45 40 40)\"><rect x=\"14\" y=\"32.5\" width=\"30\" height=\"15\" rx=\"7.5\" fill=\"currentColor\" fill-opacity=\".17\" stroke=\"currentColor\" stroke-width=\"1.4\"/><rect x=\"36\" y=\"32.5\" width=\"30\" height=\"15\" rx=\"7.5\" fill=\"currentColor\" fill-opacity=\".28\" stroke=\"currentColor\" stroke-width=\"1.4\"/><rect x=\"21\" y=\"38\" width=\"14\" height=\"4\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-opacity=\".5\"/><rect x=\"45\" y=\"38\" width=\"14\" height=\"4\" rx=\"2\" fill=\"none\" stroke=\"currentColor\" stroke-opacity=\".5\"/></g>",
  "crown": "<circle cx=\"40\" cy=\"40\" r=\"35\" fill=\"currentColor\" fill-opacity=\".06\" stroke=\"currentColor\" stroke-width=\"1.4\"/><path d=\"M40 2.5v6M40 71.5v6M2.5 40h6M71.5 40h6\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M67.6 15.3l3.2 3.2-3.2 3.2-3.2-3.2Z\" fill=\"currentColor\"/><path d=\"M25 49 22 29l9.5 7L40 23l8.5 13 9.5-7-3 20Z\" fill=\"currentColor\" fill-opacity=\"0.28\" stroke=\"currentColor\" stroke-width=\"1.4\" stroke-linejoin=\"round\"/><path d=\"M25 49h30v6H25Z\" fill=\"currentColor\" fill-opacity=\"0.48\" stroke=\"currentColor\" stroke-width=\"1.4\" stroke-linejoin=\"round\"/><path d=\"M22 23.9l2.6 2.6-2.6 2.6-2.6-2.6Z\" fill=\"currentColor\"/><path d=\"M40 16.7l2.8 2.8-2.8 2.8-2.8-2.8Z\" fill=\"currentColor\"/><path d=\"M58 23.9l2.6 2.6-2.6 2.6-2.6-2.6Z\" fill=\"currentColor\"/><path d=\"M17 63q23-8 46 0\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-opacity=\".5\"/>",
  "draft": "<circle cx=\"40\" cy=\"40\" r=\"35\" fill=\"currentColor\" fill-opacity=\".06\" stroke=\"currentColor\" stroke-width=\"1.4\"/><path d=\"M40 2.5v6M40 71.5v6M2.5 40h6M71.5 40h6\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M67.6 15.3l3.2 3.2-3.2 3.2-3.2-3.2Z\" fill=\"currentColor\"/><g transform=\"rotate(-8 30 40)\"><path d=\"M21 25h18a2 2 0 0 1 2 2v26a2 2 0 0 1-2 2H21a2 2 0 0 1-2-2V27a2 2 0 0 1 2-2Z\" fill=\"currentColor\" fill-opacity=\"0.28\" stroke=\"currentColor\" stroke-width=\"1.4\" stroke-linejoin=\"round\"/><path d=\"m24.5 40.5 4 4 7-8.5\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></g><g transform=\"rotate(8 50 40)\"><path d=\"M41 25h18a2 2 0 0 1 2 2v26a2 2 0 0 1-2 2H41a2 2 0 0 1-2-2V27a2 2 0 0 1 2-2Z\" fill=\"currentColor\" fill-opacity=\"0.1\" stroke=\"currentColor\" stroke-width=\"1.4\" stroke-linejoin=\"round\"/><path d=\"M44.5 50 55.5 30\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></g>",
  "race": "<circle cx=\"40\" cy=\"40\" r=\"35\" fill=\"currentColor\" fill-opacity=\".06\" stroke=\"currentColor\" stroke-width=\"1.4\"/><path d=\"M40 2.5v6M40 71.5v6M2.5 40h6M71.5 40h6\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M67.6 15.3l3.2 3.2-3.2 3.2-3.2-3.2Z\" fill=\"currentColor\"/><path d=\"M17 32h40M17 48h40\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1\" stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-opacity=\".5\"/><path d=\"M19 32h18M19 48h26\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><path d=\"M42 28l4 4-4 4-4-4Z\" fill=\"currentColor\"/><path d=\"M50 44l4 4-4 4-4-4Z\" fill=\"currentColor\"/><path d=\"M59 21v38\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.4\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/><rect x=\"60.5\" y=\"21\" width=\"3\" height=\"3\" fill=\"currentColor\" fill-opacity=\".48\"/><rect x=\"63\" y=\"29\" width=\"3\" height=\"3\" fill=\"currentColor\"/><rect x=\"60.5\" y=\"37\" width=\"3\" height=\"3\" fill=\"currentColor\" fill-opacity=\".48\"/><rect x=\"63\" y=\"45\" width=\"3\" height=\"3\" fill=\"currentColor\"/><rect x=\"60.5\" y=\"53\" width=\"3\" height=\"3\" fill=\"currentColor\" fill-opacity=\".48\"/>"
};
  var NAMES = {"shadow":"Shadow","flag":"Flag","daily":"Daily","link":"Challenge link","crown":"Crown","draft":"Draft","race":"Live race"};
  var LINES = {
  "shadow": "A calibrated opponent at your rating, when nobody else is online.",
  "flag": "Your set stays planted as an open challenge, and settles when someone answers.",
  "daily": "One draw a day, the same for everyone.",
  "link": "A link that opens a duel or a ghost race against you.",
  "crown": "Hold a category and band until someone beats your set.",
  "draft": "Pick and ban scenarios before the match starts.",
  "race": "Both players at once, every round revealed as it lands."
};
  function esc(s) { return String(s).replace(/[&<>"']/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]; }); }
  function a11y(o) { return o && o.label ? ' role="img" aria-label="' + esc(o.label) + '"><title>' + esc(o.label) + "</title>" : ' aria-hidden="true">'; }
  function cls(o) { return o && o.className ? ' class="' + esc(o.className) + '"' : ""; }
  function size(o) { return o && o.size ? ' width="' + Number(o.size) + '" height="' + Number(o.size) + '"' : ""; }
  function mechanicIcon(id, o) {
    if (!BODIES[id]) throw new Error("no mechanic icon " + id);
    return "<svg" + cls(o) + " " + ICON_ATTRS + size(o) + a11y(o) + BODIES[id] + "</svg>";
  }
  function mechanicEmblem(id, o) {
    if (!EMBLEMS[id]) throw new Error("no mechanic emblem " + id);
    return '<svg' + cls(o) + ' viewBox="0 0 80 80"' + size(o) + a11y(o) + EMBLEMS[id] + "</svg>";
  }
  window.APOGEE_MECHANICS = Object.freeze({ ids: Object.keys(BODIES), names: NAMES, lines: LINES, icon: mechanicIcon, emblem: mechanicEmblem });
  window.mechanicIcon = mechanicIcon;
  window.mechanicEmblem = mechanicEmblem;
  // index.html names an icon rather than drawing a copy of it; this draws it, keeping the
  // placeholder's class, so the glyph has one home in static markup too.
  function fill() {
    var els = document.querySelectorAll("[data-mechanic-icon]");
    for (var i = 0; i < els.length; i++) {
      var id = els[i].getAttribute("data-mechanic-icon");
      if (BODIES[id]) els[i].outerHTML = mechanicIcon(id, { className: els[i].getAttribute("class") || "" });
    }
  }
  if (typeof document === "undefined") return;
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", fill);
  else fill();
})();
