/**
 * Write data/shadow_days.json, the distribution Shadows are fielded from.
 *
 *   npm run build:shadows                       model, from committed measurements
 *   npm run build:shadows -- <stats folder>     corpus, replayed from a real folder
 *   npm run build:shadows -- --check            fail if the committed model is stale
 *
 * With no folder named, APOGEE_STATS_DIR and the usual Windows install paths are tried
 * first, so on the owner's machine a bare `npm run build:shadows` replaces the model with
 * the corpus build. `--model` forces the model. See src/core/match/shadowTable.ts for what
 * each method reads and why.
 *
 * The corpus build files rounds by skill: Apogee's own scenarios by the season's category,
 * and everything else by KovaaK's aim type from data/scenario_taxonomy.json.
 *
 * Two files are written from one table. data/shadow_days.json is the record a person reads;
 * src/core/match/shadowDays.ts carries the same numbers as a module, because the Edge
 * Functions import core modules and nothing in them imports JSON. `--check` holds the two
 * to each other.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { scanStatsFolder } from "../src/core/history/history.ts";
import { corpusDays, corpusTable, modelInputs, modelTable, type RoundSkill } from "../src/core/match/shadowTable.ts";
import type { ShadowTable } from "../src/core/match/shadow.ts";

const root = new URL("../", import.meta.url);
const read = (path: string) => readFileSync(new URL(path, root), "utf8");
export const SHADOW_TABLE_PATH = fileURLToPath(new URL("data/shadow_days.json", root));
export const SHADOW_MODULE_PATH = fileURLToPath(new URL("src/core/match/shadowDays.ts", root));

/** The module the server imports: the table, verbatim, with a header saying where it came from. */
export function shadowModule(table: ShadowTable): string {
  return `/**\n * Generated by tools/buildShadowTable.ts from data/shadow_days.json. Do not edit by hand:\n` +
    ` * run npm run build:shadows. The Edge Functions read the Shadow table from here because\n` +
    ` * they import core modules and never JSON.\n */\n\n` +
    `import type { ShadowTable } from "./shadow.ts";\n\n` +
    `export const SHADOW_DAYS: ShadowTable = ${JSON.stringify(table)};\n`;
}

export function buildModel(builtAt: string): ShadowTable {
  return modelTable(
    modelInputs(read("src/core/history/baseline.ts"), read("docs/overnight/mechanics.md"), JSON.parse(read("data/fun_audit.json"))),
    builtAt,
  );
}

/** Scenario name to skill, for the corpus build. */
export function scenarioSkills(): (name: string) => RoundSkill | null {
  const bySkill = new Map<string, RoundSkill>();
  const taxonomy = JSON.parse(read("data/scenario_taxonomy.json"));
  for (const s of taxonomy.scenarios ?? []) {
    const aim = String(s.aimType ?? "");
    const skill: RoundSkill | null = aim === "Clicking" ? "Clicking" : aim === "Tracking" ? "Tracking"
      : /Switching/.test(aim) ? "Switching" : null;
    if (skill) bySkill.set(String(s.name).trim(), skill);
  }
  const season = JSON.parse(read("data/seasons/season-1.json"));
  for (const s of season.scenarios ?? []) {
    const skill = String(s.category ?? "").split(" ").pop() as RoundSkill;
    if (skill === "Clicking" || skill === "Tracking" || skill === "Switching") bySkill.set(s.scenario, skill);
  }
  return (name) => bySkill.get(name.trim()) ?? null;
}

export function buildCorpus(statsDir: string, builtAt: string): ShadowTable {
  return corpusTable(corpusDays(scanStatsFolder(statsDir), scenarioSkills()), builtAt);
}

function main(): void {
  const args = process.argv.slice(2);
  const check = args.includes("--check");
  const forceModel = args.includes("--model") || check;
  const named = args.find((a) => !a.startsWith("--"));
  const statsDir = forceModel ? null : [
    named,
    process.env.APOGEE_STATS_DIR,
    "E:\\Steam\\steamapps\\common\\FPSAimTrainer\\FPSAimTrainer\\stats",
    "C:/Program Files (x86)/Steam/steamapps/common/FPSAimTrainer/FPSAimTrainer/stats",
  ].find((p): p is string => Boolean(p) && existsSync(p!)) ?? null;
  if (named && !statsDir && !forceModel) throw new Error(`no stats folder at ${named}`);

  if (check) {
    const committed = JSON.parse(readFileSync(SHADOW_TABLE_PATH, "utf8")) as ShadowTable;
    if (committed.method !== "model") {
      const moduleSame = existsSync(SHADOW_MODULE_PATH) && readFileSync(SHADOW_MODULE_PATH, "utf8") === shadowModule(committed);
      console.log(`data/shadow_days.json is a corpus build (${committed.builtAt}); nothing to regenerate without its folder`);
      console.log(moduleSame ? "OK: src/core/match/shadowDays.ts matches data/shadow_days.json" : "FAIL: src/core/match/shadowDays.ts is stale");
      if (!moduleSame) process.exit(1);
      return;
    }
    const fresh = buildModel(committed.builtAt);
    const same = JSON.stringify(fresh) === JSON.stringify(committed);
    const moduleSame = existsSync(SHADOW_MODULE_PATH) && readFileSync(SHADOW_MODULE_PATH, "utf8") === shadowModule(committed);
    console.log(same ? "OK: data/shadow_days.json matches its committed inputs" : "FAIL: data/shadow_days.json is stale; run npm run build:shadows");
    console.log(moduleSame ? "OK: src/core/match/shadowDays.ts matches data/shadow_days.json" : "FAIL: src/core/match/shadowDays.ts is stale; run npm run build:shadows");
    if (!same || !moduleSame) process.exit(1);
    return;
  }

  const builtAt = new Date().toISOString();
  const table = statsDir ? buildCorpus(statsDir, builtAt) : buildModel(builtAt);
  writeFileSync(SHADOW_TABLE_PATH, JSON.stringify(table, null, 1) + "\n");
  writeFileSync(SHADOW_MODULE_PATH, shadowModule(table));
  const q = (k: "k1" | "k3", p: number) => `${(table.skills.All[k][p - 1] * 100).toFixed(2)}%`;
  console.log(`wrote data/shadow_days.json and src/core/match/shadowDays.ts (${table.method}${statsDir ? ` from ${statsDir}` : ""})`);
  console.log(`  three-round day, all skills: p20 ${q("k3", 20)}  p50 ${q("k3", 50)}  p80 ${q("k3", 80)}  p95 ${q("k3", 95)}`);
  console.log(`  single round, all skills:    p20 ${q("k1", 20)}  p50 ${q("k1", 50)}  p80 ${q("k1", 80)}`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();
