"""Derive the Voltaic sub-category mapping from Voltaic's own published spreadsheet.

The nine sub-categories drive the weakness map and decide which scenarios a
sub-category queue can draw from, so getting them wrong quietly corrupts both. An
earlier version of data/subcategories.json was derived by reading scenario descriptions
and was wrong on 6 of 18 scenarios, notably swapping Tracking's Precise and Reactive
groups entirely.

This reads the mapping from the source instead. evxl's registry records each benchmark's
`spreadsheetURL`; for Voltaic S5 that is Voltaic's own public sheet, exportable as CSV.
Its first three columns are skill / sub-category / scenario, using merged cells, so the
labels are forward-filled down each group.

    python tools/fetch_voltaic_subcategories.py

Output: data/subcategories.json
"""

from __future__ import annotations

import csv
import io
import json
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "data" / "evxl_registry.json"
OUT = ROOT / "data" / "subcategories.json"

BENCHMARK = "Voltaic S5"
UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/126.0 Safari/537.36"

SKILLS = {"Clicking", "Tracking", "Switching"}
SUBCATEGORIES = {
    "Dynamic", "Static", "Linear",
    "Precise", "Reactive", "Control",
    "Speed", "Evasive", "Stability",
}


def sheet_id(url: str) -> str | None:
    m = re.search(r"/spreadsheets/d/([A-Za-z0-9_-]+)", url or "")
    return m.group(1) if m else None


def fetch_csv(sheet: str) -> str:
    export = f"https://docs.google.com/spreadsheets/d/{sheet}/export?format=csv"
    req = urllib.request.Request(export, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read().decode("utf-8", "replace")


def family_of(scenario: str) -> str:
    """'VT Pasu Novice' -> 'Pasu'. The sheet omits the ' S5' the game appends."""
    stem = re.sub(r"^VT\s+", "", scenario.strip())
    stem = re.sub(r"\s*S5(\.5)?\s*$", "", stem, flags=re.I)
    stem = re.sub(
        r"\s*\b(Novice|Intermediate|Advanced|Elite)\b\s*", " ", stem, flags=re.I
    )
    return stem.strip()


def parse(csv_text: str) -> list[tuple[str, str, str]]:
    """Forward-fill the merged skill / sub-category cells down each group."""
    rows = list(csv.reader(io.StringIO(csv_text)))
    skill: str | None = None
    sub: str | None = None
    out: list[tuple[str, str, str]] = []

    for row in rows:
        if len(row) < 3:
            continue
        a, b, c = row[0].strip(), row[1].strip(), row[2].strip()

        if a in SKILLS:
            skill = a
            # A new skill begins a new sub-category run.
            sub = None
        if b in SUBCATEGORIES:
            sub = b

        if c.startswith("VT ") and skill and sub:
            out.append((skill, sub, c))

    return out


def main() -> int:
    registry = json.loads(REGISTRY.read_text(encoding="utf-8"))["benchmarks"]
    entry = next((b for b in registry if b["benchmarkName"] == BENCHMARK), None)
    if entry is None:
        print(f"{BENCHMARK} not in the evxl registry", file=sys.stderr)
        return 1

    sheet = sheet_id(entry.get("spreadsheetURL") or "")
    if not sheet:
        print(f"no spreadsheet URL recorded for {BENCHMARK}", file=sys.stderr)
        return 1

    print(f"source: {entry['spreadsheetURL']}")
    triples = parse(fetch_csv(sheet))

    if not triples:
        print("no scenario rows found - the sheet layout may have changed", file=sys.stderr)
        return 1

    families: dict[str, dict[str, str]] = {}
    for skill, sub, scenario in triples:
        fam = family_of(scenario)
        if not fam:
            continue
        families[fam] = {"skill": skill, "subCategory": sub}

    # The 1wXts family is named per difficulty (1w4ts / 1w3ts / 1w2ts) and the sheet
    # only lists one. They are the same scenario at three difficulties, so the mapping
    # carries across.
    for variant in ("1w4ts", "1w3ts", "1w2ts"):
        known = next((families[k] for k in families if re.fullmatch(r"1w\dts", k)), None)
        if known:
            families[variant] = dict(known)

    by_sub: dict[str, list[str]] = {}
    for fam, info in families.items():
        by_sub.setdefault(f"{info['skill']}/{info['subCategory']}", []).append(fam)

    OUT.write_text(
        json.dumps(
            {
                "$comment": [
                    "Sub-category mapping for Voltaic S5, keyed by scenario family (the",
                    "name with the 'VT ' prefix and ' <Difficulty> S5' suffix removed).",
                    "",
                    "AUTHORITATIVE. Generated by tools/fetch_voltaic_subcategories.py from",
                    "Voltaic's own published spreadsheet, recorded in evxl's registry as",
                    f"{entry['spreadsheetURL']}",
                    "",
                    "Do not hand-edit. Regenerate instead, so the mapping stays traceable",
                    "to its source. An earlier hand-derived version - inferred from",
                    "scenario descriptions - was wrong on 6 of 18 scenarios: it swapped",
                    "Tracking's Precise and Reactive groups, and swapped DriftTS with",
                    "Penta Bounce between Evasive and Stability.",
                ],
                "benchmark": BENCHMARK,
                "provisional": False,
                "source": entry["spreadsheetURL"],
                "families": dict(sorted(families.items())),
            },
            indent=2,
        ),
        encoding="utf-8",
    )

    print(f"\nwrote {len(families)} families -> data/subcategories.json\n")
    for group in sorted(by_sub):
        print(f"  {group:22} {', '.join(sorted(by_sub[group]))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
