const {app,BrowserWindow}=require('electron');
const {readFileSync,writeFileSync,mkdirSync,mkdtempSync}=require('node:fs');
const {resolve,join}=require('node:path');
const {tmpdir}=require('node:os');
const assert=require('node:assert/strict');
const output=resolve('.cache/mixtape-ui');mkdirSync(output,{recursive:true});
app.setPath('userData',mkdtempSync(join(tmpdir(),'apogee-mixtape-')));
let win;const run=s=>win.webContents.executeJavaScript(s,true);const settle=()=>new Promise(r=>setTimeout(r,400));
const click=async(selector)=>{assert.ok(await run(`(()=>{const el=document.querySelector(${JSON.stringify(selector)});if(!el||el.disabled||!el.checkVisibility())return false;el.click();return true})()`),'Available control: '+selector);await settle();};
app.whenReady().then(async()=>{
  const errors=[];
  win=new BrowserWindow({show:false,width:1440,height:1080,webPreferences:{offscreen:true,backgroundThrottling:false}});
  win.webContents.on('console-message',(_,level,message)=>{if(level>=3)errors.push(message);});
  // Only this final feature script gets a synthetic bridge; ranked preview stays untouched.
  const fixture=readFileSync('tools/apogee-ui-preview.html','utf8').replace('<script>/* Mixtape:',`<script>window.__mixLaunches=[];window.__mixHandlers=[];window.apogee={onRun:fn=>window.__mixHandlers.push(fn),launchScenario:async name=>{window.__mixLaunches.push(name);return {ok:true};}};/* Mixtape:`);
  assert.ok(fixture.includes('window.__mixHandlers=[]'));
  writeFileSync(join(output,'fixture.html'),fixture);await win.loadFile(join(output,'fixture.html'));await settle();
  await click('.tab[data-screen="mixtape"]');
  assert.equal(await run(`document.querySelectorAll('.mix-track').length`),6);
  for(const [width,height] of [[1440,1080],[940,640],[600,900]]) {
    win.setSize(width,height);await settle();
    assert.ok(await run(`document.querySelector('.scroll').scrollWidth<=document.querySelector('.scroll').clientWidth+2`),'Mixtape fits '+width);
    assert.equal(await run(`document.querySelector('#screen-mixtape').classList.contains('active')`),true);
    assert.ok(await run(`(()=>{const s=document.querySelector('.mix-sleeve').getBoundingClientRect(),p=document.querySelector('.mix-sleeve-title p').getBoundingClientRect();return p.bottom<s.bottom&&p.right<=s.right})()`),'Sleeve copy fits '+width);
    writeFileSync(join(output,`builder-${width}.png`),(await win.webContents.capturePage()).toPNG());
  }
  win.setSize(1440,1080);await settle();
  const before=await run(`document.querySelector('.mix-tracklist').innerText`);
  await click('[data-mix="remix"]');assert.notEqual(await run(`document.querySelector('.mix-tracklist').innerText`),before,'Remix changes tracks');
  await click('[data-mix="mood"][data-value="push"]');await click('[data-mix="count"][data-value="3"]');
  assert.equal(await run(`document.querySelectorAll('.mix-track').length`),3);
  await run(`document.querySelector('[data-mix="band"]').value='1';document.querySelector('[data-mix="band"]').dispatchEvent(new Event('change',{bubbles:true}))`);await settle();
  assert.ok(await run(`document.querySelectorAll('.mix-why').length===3`),'Every planned track says why it is in the set');
  await click('[data-mix="start"]');assert.equal(await run(`JSON.parse(localStorage.getItem('apogee.mixtape.v1')).active.band`),1);
  assert.equal(await run(`window.__mixLaunches.length`),1,'Starting opens track 1');
  assert.ok(await run(`document.querySelector('.mix-listening').textContent.includes('Listening for your run')`),'The set says it is listening');
  await click('[data-mix="launch"]');assert.equal(await run(`window.__mixLaunches.length`),2);assert.equal(await run(`JSON.parse(localStorage.getItem('apogee.mixtape.v1')).active.index`),0,'Launch does not count a run');
  await run(`window.__mixHandlers[0]({scenario:'unrelated',score:10,playedAt:new Date().toISOString(),file:'wrong'})`);
  assert.equal(await run(`JSON.parse(localStorage.getItem('apogee.mixtape.v1')).active.index`),0);
  const receive=`(()=>{const s=JSON.parse(localStorage.getItem('apogee.mixtape.v1')).active;window.__mixHandlers[0]({scenario:s.tracks[s.index].scenario,score:(s.tracks[s.index].reference||0)+25,playedAt:new Date().toISOString(),file:'receipt-'+s.index})})()`;
  await run(receive);await settle();assert.equal(await run(`JSON.parse(localStorage.getItem('apogee.mixtape.v1')).active.index`),1);
  assert.ok(await run(`/RUN RECEIVED/.test(document.querySelector('.mix-signal').textContent)&&/Up next/.test(document.querySelector('.mix-signal').textContent)`),'A landed run gets a verdict and names the next track');
  assert.equal(await run(`!!document.querySelector('.mix-listening')`),false,'A landed run ends the listening state');
  writeFileSync(join(output,'playing.png'),(await win.webContents.capturePage()).toPNG());
  await run(`(()=>{const s=JSON.parse(localStorage.getItem('apogee.mixtape.v1')).active;window.__mixHandlers[0]({scenario:s.tracks[2].scenario,score:1,playedAt:new Date().toISOString(),file:'early'})})()`);await settle();
  assert.ok(await run(`document.querySelector('.mix-signal').textContent.includes('That was track 3')`),'A later track played early is explained, not ignored');
  assert.equal(await run(`JSON.parse(localStorage.getItem('apogee.mixtape.v1')).active.index`),1,'and does not count');
  await win.reload();await settle();assert.equal(await run(`JSON.parse(localStorage.getItem('apogee.mixtape.v1')).active.index`),1,'Resume after reload');
  await click('[data-mix="skip"]');await run(receive);await settle();
  assert.equal(await run(`JSON.parse(localStorage.getItem('apogee.mixtape.v1')).active`),null);
  assert.equal(await run(`JSON.parse(localStorage.getItem('apogee.mixtape.v1')).history.length`),1);
  assert.equal(await run(`document.querySelectorAll('.mix-recap .mix-track.played').length`),2);
  assert.equal(await run(`document.querySelectorAll('.mix-recap .mix-track.skipped').length`),1);
  writeFileSync(join(output,'recap.png'),(await win.webContents.capturePage()).toPNG());
  const played=await run(`JSON.parse(localStorage.getItem('apogee.mixtape.v1')).history[0].tracks.map(t=>t.scenario)`);
  await click('[data-mix="again"]');
  assert.deepEqual(await run(`JSON.parse(localStorage.getItem('apogee.mixtape.v1')).active.tracks.map(t=>t.scenario)`),played,'Run it back replays the same tracks in order');
  await click('[data-mix="end"]');
  await click('[data-mix="history"]');assert.equal(await run(`!!document.querySelector('.mix-recap')`),true,'History opens saved recap');
  await click('[data-mix="new"]');await click('[data-mix="start"]');
  await run(`window.apogee.launchScenario=async()=>({error:'Test launch unavailable'});true`);await click('[data-mix="launch"]');
  assert.ok(await run(`document.querySelector('.mix-message').textContent.includes('Test launch unavailable')`),'Launch failure is visible');
  assert.equal(await run(`JSON.parse(localStorage.getItem('apogee.mixtape.v1')).active.index`),0,'Launch error cannot complete a track');
  await click('[data-mix="end"]');
  assert.equal(await run(`!!document.querySelector('.mix-recap')`),false,'An unplayed set is not filed as a recap');
  await click('[data-mix="start"]');
  for(let i=0;i<3;i++){await run(receive);await settle();}
  assert.equal(await run(`document.querySelector('.mix-recap h2').textContent`),'That’s a wrap.','Full-set completion');
  assert.equal(await run(`document.querySelectorAll('.mix-burst i').length`),16,'Completion burst accompanies a fully played set');
  await win.webContents.debugger.attach('1.3');await win.webContents.debugger.sendCommand('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});
  await click('[data-mix="new"]');await click('[data-mix="start"]');assert.equal(await run(`getComputedStyle(document.querySelector('.mix-record')).animationName`),'none');
  win.webContents.debugger.detach();
  // A set saved before the season changed: its retired scenario is skipped, with the reason.
  await run(`(()=>{const s=JSON.parse(localStorage.getItem('apogee.mixtape.v1'));s.active.tracks[0].scenario='Retired Scenario';s.active.tracks[0].label='Retired Scenario';localStorage.setItem('apogee.mixtape.v1',JSON.stringify(s));return true})()`);
  await win.reload();await settle();
  await run(`window.dispatchEvent(new CustomEvent('apogee:practice-ready',{detail:window.__APOGEE_PRACTICE__}));true`);await settle();
  assert.ok(await run(`document.querySelector('.mix-message').textContent.includes('left the season pool')`),'A retired scenario is skipped with the reason');
  assert.equal(await run(`JSON.parse(localStorage.getItem('apogee.mixtape.v1')).active.tracks[0].status`),'skipped','The retired track is skipped, not played');
  // A set saved by the build before tracks carried best and threshold reads as a real best, never NaN.
  await run(`(()=>{const s=JSON.parse(localStorage.getItem('apogee.mixtape.v1'));for(const t of s.active.tracks){delete t.best;delete t.threshold;delete t.thresholdIndex;t.reference=1234;t.referenceLabel='Personal best';t.target=1500}localStorage.setItem('apogee.mixtape.v1',JSON.stringify(s));return true})()`);
  await win.reload();await settle();
  await run(`window.dispatchEvent(new CustomEvent('apogee:practice-ready',{detail:window.__APOGEE_PRACTICE__}));true`);await settle();
  assert.ok(!(await run(`document.body.innerText.includes('NaN')`)),'An older saved set renders without NaN');
  assert.ok(await run(`document.body.innerText.includes('1,234')`),'and shows its saved best');
  // Auto-open: a recorded run opens the next track without a trip back to Apogee.
  await run(`window.__opened=[];window.apogee.launchScenario=async(s)=>{window.__opened.push(s);return {ok:true}};true`);
  await click('[data-mix="auto"]');
  const nextUp=await run(`JSON.parse(localStorage.getItem('apogee.mixtape.v1')).active.tracks[2].scenario`);
  await run(receive);await settle();
  assert.deepEqual(await run(`window.__opened`),[nextUp],'Auto-open launches the next track after a recorded run');
  await click('[data-mix="auto"]');
  await click('[data-mix="end"]');
  await run(`localStorage.setItem('apogee.mixtape.v1','{"active":{"version":1,"tracks":null},"history":[{}]}')`);
  await win.reload();await settle();assert.equal(await run(`document.querySelectorAll('.mix-track').length`),6,'Corrupt saved state recovers');
  await run(`window.dispatchEvent(new CustomEvent('apogee:practice-ready',{detail:{season:{windows:['Novice','Intermediate','Advanced','Expert']},scenarios:[],playlistDir:null}}))`);await settle();
  assert.equal(await run(`document.querySelector('[data-mix="start"]').disabled`),true,'Empty pool cannot start');
  await run(`window.apogee.chooseFolder=async()=>null;window.dispatchEvent(new CustomEvent('apogee:practice-ready',{detail:{...window.__APOGEE_PRACTICE__,playlistDir:null}}));true`);await settle();
  await click('[data-mix="start"]');await click('[data-mix="folder"]');
  assert.ok(await run(`document.querySelector('.mix-message').textContent.includes('cancelled')`),'Cancelled folder selection is reported honestly');
  await click('[data-mix="end"]');
  await run(`Storage.prototype.setItem=function(){throw Error('Test storage blocked')};true`);
  await click('[data-mix="start"]');assert.ok(await run(`document.querySelector('.mix-message').textContent.includes('running in memory')`),'Storage failure is visible');
  await run(`document.getElementById('app').hidden=true;document.querySelector('.tab[data-screen="mixtape"]').click()`);
  assert.equal(await run(`document.getElementById('mixtapeRoot').checkVisibility()`),true,'Accessible without snapshot');
  await run(`document.getElementById('empty').hidden=false`);
  assert.equal(await run(`getComputedStyle(document.getElementById('empty')).display`),'none','Onboarding panel does not displace Mixtape');
  assert.deepEqual(errors,[],'Renderer errors');console.log('PASS: Mixtape builder, remix, mood, band, length, exact launch, run tracking, reload, skip, recap, history, reduced motion, corrupt storage, onboarding and three responsive screenshots.');app.exit(0);
}).catch(error=>{console.error(error);app.exit(1);});
