let count = 0;
const check = (ok, message) => { if (!ok) throw new Error(message); count++; };
const frame = () => new Promise(r => requestAnimationFrame(() => requestAnimationFrame(r)));
const initial = gridSnapshot();
const reset = () => {
  gridCancelCuts(); const s = JSON.parse(initial);
  seasonDraft = s.season; seasonPercentiles = s.ladder; rankTheme = s.rankTheme;
  gridSel = {family:familyKeyOf(seasonDraft.scenarios[0]),window:0};
  gridFilter = 'all'; gridCategory = ''; gridUndo.length = 0; gridRedo.length = 0;
  renderSeasonEditor();
};
reset();
await frame();
check($('poolGrid').checkVisibility(), 'Editor grid must be visibly rendered');
const first = gridSlot(gridSel.family,0), originalName = first.scenario;
$('poolGrid').focus();
$('poolGrid').dispatchEvent(new KeyboardEvent('keydown',{key:'Delete',bubbles:true}));
check(gridSlot(gridSel.family,0).scenario === '', 'Delete clears the scenario');
check(gridUndo.length === 1, 'Clear creates one undo step');
check($('seasonSave').disabled, 'Empty slot prevents saving');
gridStep(-1);
check(gridSlot(gridSel.family,0).scenario === originalName, 'Undo restores cleared scenario');
gridStep(1);
check(gridSlot(gridSel.family,0).scenario === '', 'Redo clears it again');
gridStep(-1);
check(editorAddCategory('Custom Clicking'), 'Add category');
check(seasonDraft.categories.at(-1).name === 'Custom Clicking', 'New category exists');
check(seasonDraft.scenarios.filter(s=>s.category==='Custom Clicking').length===4, 'New category has an initial family in all windows');
check(seasonDraft.scenarios.filter(s=>s.category==='Custom Clicking')[0].rankMaxes.length===6, 'New slots include overlap thresholds');
check(seasonDraft.categories.at(-1).bands.length===4, 'New category has playable bands');
gridStep(-1);
check(!seasonDraft.categories.some(c=>c.name==='Custom Clicking'), 'Category creation undoes completely');
gridStep(1);
const category = seasonDraft.categories.at(-1);
check(editorRenameCategory(category,'Custom Tracking'), 'Category rename');
check(seasonDraft.scenarios.filter(s=>s.category==='Custom Tracking').length===4, 'Rename moves every scenario');
check(!editorRenameCategory(category,seasonDraft.categories[0].name), 'Duplicate category names rejected');
check(!editorRenameCategory(category,'invalid/name'), 'Ambiguous category keys rejected');
editorRemoveCategory(category);
check(!seasonDraft.categories.some(c=>c.name==='Custom Tracking'), 'Category removal');
gridStep(-1);
check(seasonDraft.categories.some(c=>c.name==='Custom Tracking'), 'Category removal restores through undo');
reset();
const key = gridSel.family, nextCategory = seasonDraft.categories[1].name;
const beforeBandEnergy = seasonDraft.categories[0].bands[0].rankMaxes[0];
editorMoveFamily(key,nextCategory);
check(gridSel.family.startsWith(nextCategory+'/'), 'Move selects new family location');
check(seasonDraft.categories[0].bands[0].rankMaxes[0] < beforeBandEnergy, 'Moving family rebalances playable band energy');
check(seasonDraft.$renamed[gridSel.family]===key, 'Move retains metadata lineage');
gridStep(-1);
check(gridSlot(key,0)?.scenario===originalName, 'Move undo restores category and scenarios');
reset();
gridRemember();addWindow('Master');editorStructureChanged();
check(seasonDraft.windows.length===5, 'Add difficulty');
check(seasonPercentiles.ranks.length===20, 'Percentile ladder extends with difficulty');
check(seasonPercentiles.ranks.every((n,i,a)=>i===0||n<a[i-1]), 'Extended percentile shares descend');
check(seasonDraft.categories.every(c=>c.bands.length===5), 'Every category receives a playable band');
check(seasonDraft.categories.every(c=>c.bands.at(-1).positional && !c.bands.at(-2).positional), 'Positional rank belongs only to hardest band');
check(seasonDraft.scenarios.filter(s=>s.window===3).every(s=>s.rankMaxes.length===6), 'Former top gains overlap thresholds');
gridStep(-1);
check(seasonDraft.windows.length===4 && seasonPercentiles.ranks.length===16, 'Undo restores window and percentile structure');
gridRemember();removeWindow();editorStructureChanged();
check(seasonDraft.windows.length===3, 'Remove difficulty');
check(seasonDraft.scenarios.filter(s=>s.window===2).every(s=>s.rankMaxes.length===4), 'New top truncates overlap');
check(seasonDraft.categories.every(c=>c.bands.length===3), 'Remove difficulty updates bands');
gridStep(-1);
reset();
const sourceNames = seasonDraft.scenarios.slice(0,4).map(s=>s.scenario);
check(editorPaste(sourceNames.slice().reverse().join('\t')), 'Spreadsheet row paste');
check(gridSlot(gridSel.family,0).scenario===sourceNames[3], 'Paste replaces first cell');
check(gridUndo.length===1, 'One undo for entire paste');
gridStep(-1);
check(gridSlot(gridSel.family,0).scenario===originalName, 'Paste undo restores all cells');
const beforeBadPaste=JSON.stringify(seasonDraft);
check(!editorPaste(sourceNames[1]+'\tunknown scenario that does not exist'), 'Unknown name rejects paste');
check(JSON.stringify(seasonDraft)===beforeBadPaste, 'Failed paste is atomic');
check(editorPaste(sourceNames.slice().reverse().join('\n')), 'Line separated list paste');
check(gridSlot(gridSel.family,3).scenario===sourceNames[0], 'List fills in reading order');
reset();
gridSelect(gridFamilies().at(-1).key,3);
check(gridAdvance(1)===false && gridSel.window===3, 'Last slot does not wrap and overwrite first in row');
gridSelect(gridFamilies()[0].key,0);
check(gridAdvance(-1)===false && gridSel.window===0, 'First slot does not wrap backward');
gridOpenSearch('test scenario 120');
const nodes=[...$('poolGridHits').children];
$('poolGridQuery').dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));
check([...$('poolGridHits').children].every((n,i)=>n===nodes[i]), 'Search arrows reuse results instead of rebuilding');
check($('poolGridQuery').getAttribute('aria-activedescendant')==='pool-hit-1', 'Search exposes active option');
gridCloseSearch(false);
check($('poolGridQuery').getAttribute('aria-expanded')==='false','Combobox closes accessibly');
reset();
let resolveBoard;
const originalSample = window.apogee.sampleScenario;
window.apogee.sampleScenario = () => new Promise(r=>{resolveBoard=r;});
gridRemember();
gridReplace(gridSlot(gridSel.family,0),{name:'Delayed board',leaderboardId:100});
check(gridWaiting().cutting===1,'Replacement queues background thresholds');
await frame();
gridCancelCut(gridSlot(gridSel.family,0));
gridSlot(gridSel.family,0).rankMaxes=[10,20,30,40,50,60];
gridSlot(gridSel.family,0).source={kind:'authored',why:'Manual thresholds for test'};
resolveBoard({rankMaxes:[100,200,300,400,500,600],entries:10000});
await frame();
check(gridSlot(gridSel.family,0).rankMaxes[0]===10,'Late board cannot overwrite manual thresholds');
window.apogee.sampleScenario=originalSample;
reset();
gridCuts.set(cutKeyOf(gridSlot(gridSel.family,0)),{state:'check',message:'Flat thresholds'});
seasonDirty(true);
check($('seasonSave').disabled, 'Flat thresholds prevent saving');
gridCuts.clear();
// Recovery must keep the original disk fingerprint so stale drafts cannot bypass the save conflict check.
seasonFingerprint='test-original-fingerprint';
seasonDraft.name='Recovery test';
seasonDirty(true);
window.dispatchEvent(new Event('pagehide'));
const recovery=JSON.parse(localStorage.getItem(SEASON_DRAFT_KEY));
check(recovery.name==='Recovery test', 'Pending draft backup flushes on exit');
check(recovery.$editor.fingerprint==='test-original-fingerprint','Draft backup retains conflict fingerprint');
clearStashedDraft();
check(seasonStashTimer===null,'Clearing backup cancels deferred writes');
reset();
seasonDirty(true);
let finishSave, submitted;
window.apogee.saveSeason = (draft) => { submitted=draft; return new Promise(r=>{finishSave=r;}); };
const saving = saveSeasonDraft();
check(seasonSaving && $('seasonSave').disabled, 'Save prevents duplicate submissions');
const submittedName=submitted.name;
seasonDraft.name='Edit made during save';seasonDirty(true);
check(submitted.name===submittedName,'Save sends an immutable draft snapshot');
finishSave({fingerprint:'saved-v2',path:'isolated-test.json'});
await saving;
check(seasonDraft.name==='Edit made during save' && !$('seasonReload').disabled, 'Edits during save remain dirty');
check(seasonFingerprint==='saved-v2', 'Successful save advances disk fingerprint');
check(!!localStorage.getItem(SEASON_DRAFT_KEY), 'Concurrent edits retain recovery backup');
window.apogee.saveSeason=async()=>{throw new Error('Synthetic IPC failure');};
await saveSeasonDraft();
check(!seasonSaving && !$('seasonSave').disabled,'Rejected save releases busy state and allows retry');
check($('seasonStatus').textContent.includes('Synthetic IPC failure'),'Rejected save explains the failure');
window.apogee.saveSeason=async()=>({error:'Disk changed',stale:true});
await saveSeasonDraft();
check(seasonForce,'Stale save offers explicit second-save override');
window.apogee.saveSeason=async()=>({fingerprint:'saved-v3',path:'isolated-test.json'});
await saveSeasonDraft();
check(!seasonForce && $('seasonSave').disabled,'Successful retry clears dirty state and force flag');
check(!localStorage.getItem(SEASON_DRAFT_KEY),'Successful save clears backup without delayed resurrection');
reset();
const batchBefore=seasonDraft.scenarios.length;
check(editorAddFamilies(seasonDraft.categories[0].name,'Batch One\nBatch Two')===null,'Batch family creation');
check(seasonDraft.scenarios.length===batchBefore+8,'Two families create eight slots');
check(gridUndo.length===1,'Batch families create one undo step');
gridStep(-1);
check(seasonDraft.scenarios.length===batchBefore,'Batch family undo');
check(!!editorAddFamilies(seasonDraft.categories[0].name,'Unique Family\nUnique Family'),'Duplicate batch names rejected');
check(seasonDraft.scenarios.length===batchBefore,'Rejected family batch changes nothing');
const exported={format:'apogee-season-draft',version:1,season:structuredClone(seasonDraft),ladder:structuredClone(seasonPercentiles),rankTheme:null};
exported.season.name='Imported season';
editorImportDraft(exported);
check(seasonDraft.name==='Imported season','Draft import restores exported season');
gridStep(-1);
check(seasonDraft.name!==exported.season.name,'Draft import is undoable');
const beforeInvalidImport=JSON.stringify(seasonDraft);
let refused=false;
try { editorImportDraft({format:'nope'}); } catch { refused=true; }
check(refused && JSON.stringify(seasonDraft)===beforeInvalidImport,'Invalid import preserves working draft');
reset();
const thresholdSlot=gridSlot(gridSel.family,0), oldThresholds=thresholdSlot.rankMaxes.slice();
check(editorPasteThresholds(thresholdSlot,0,[100,200,300,400,500,600]),'Threshold row paste');
check(thresholdSlot.rankMaxes[5]===600,'Threshold paste fills all ranks');
gridStep(-1);
check(JSON.stringify(gridSlot(gridSel.family,0).rankMaxes)===JSON.stringify(oldThresholds),'Threshold paste is undoable');
check(!editorPasteThresholds(gridSlot(gridSel.family,0),0,[300,200]),'Descending threshold paste rejected');
reset();
await frame();
const savedSeason = structuredClone(seasonDraft), savedLadder = structuredClone(seasonPercentiles), savedCatalogue = seasonAvailable;
window.apogee.getSeason = async()=>({season:structuredClone(savedSeason),ladder:structuredClone(savedLadder),fingerprint:'loaded-fingerprint',path:'isolated-season.json'});
window.apogee.availableScenarios=async()=>({scenarios:savedCatalogue,windowed:true});
clearStashedDraft();
await loadSeasonEditor();
check(!seasonHasChanges && $('seasonSave').disabled,'Loading an unchanged season does not mark it dirty');
check(seasonStashTimer===null,'Clean load does not leave a deferred backup');
let completeCatalogue;
window.apogee.availableScenarios=()=>new Promise(r=>{completeCatalogue=r;});
const loading=loadSeasonEditor();
await frame();
$('poolGridDetail').querySelector('details').open=true;
await frame();
const label=$('poolGridDetail').querySelector('.editor-field input');
label.focus();label.value='Edit while catalogue loads';label.dispatchEvent(new Event('change'));
completeCatalogue({scenarios:savedCatalogue,windowed:true});
await loading;
check(seasonHasChanges,'Edits during catalogue loading remain dirty');
check(document.activeElement===label && label.isConnected,'Catalogue loading preserves the active editor field');
gridDetailsOpen=false; reset(); clearStashedDraft(); seasonDirty(false); setSeasonStatus('','');
await frame();
gridSelect(gridFamilies()[1].key,2);
$('poolGrid').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',shiftKey:true,bubbles:true}));
check(Number(document.activeElement.value)===gridSlot(gridSel.family,2).rankMaxes[0],'Immediate Shift+Enter edits the newly selected slot');
$('poolGrid').focus();
await frame();
$('poolGrid').scrollTop=250;
const scrolled=$('poolGrid').scrollTop;
renderPoolGrid(); await frame();
check(Math.abs($('poolGrid').scrollTop-scrolled)<2,'Grid redraw preserves scroll position without forced layout');
reset(); clearStashedDraft(); seasonDirty(false); setSeasonStatus('','');
await frame();
return `${count} season editor workflow checks passed.`;
