import assert from 'node:assert/strict';
await import('../src/app/renderer/mixtape-engine.js');
const m=globalThis.ApogeeMixtape;
const rows=Array.from({length:36},(_,i)=>({scenario:'Scenario '+i,label:'Track '+i,category:'Category '+i%6,family:'Family '+i,window:i<24?0:1,last:i===0?0:100,best:150,nextRankScore:151+i,runs:i%4}));
let checks=0;
const check=(actual,expected,message)=>{assert.deepEqual(actual,expected,message);checks++;};
for(const mood of ['balance','push','discover']) for(const count of [3,6,9]) {
  const plan=m.plan(rows,{mood,count,band:0,seed:17});
  check(plan.length,count,'Requested length');
  check(new Set(plan.map(t=>t.scenario)).size,count,'No duplicate scenarios');
  check(plan.every(t=>rows.find(r=>r.scenario===t.scenario).window===0),true,'Exact difficulty');
  check(plan,m.plan(rows,{mood,count,band:0,seed:17}),'Deterministic remix');
}
check(new Set(m.plan(rows,{count:6}).map(t=>t.category)).size,6,'Balanced circuit visits all available categories');
check(m.plan(rows,{mood:'push'})[0].scenario,'Scenario 0','Closest relative gap first');
check(m.plan(rows,{mood:'discover',count:3}).every(t=>t.runs===0),true,'Unplayed scenarios first');
check(m.plan(rows,{band:3}).length,0,'No fallback to wrong band');
check(m.plan(rows,{count:999}).length,0,'Invalid count refused');
check(m.plan([...rows,rows[0]],{count:9}).length,9,'Duplicate input deduped');
check(m.plan([{...rows[0],family:'same'},{...rows[1],family:'same'},{...rows[2],family:'different'}],{count:3}).length,3,'Small pool remains usable');
check(m.plan(rows,{mood:'push'})[0].reference,0,'Zero is a real reference');
let session=m.create(m.plan(rows,{count:3,mood:'push'}),'push',0,100000);
check(m.valid(session),true,'Created session is restorable');
const first=session.tracks[0].scenario;
const run=(scenario,at,score=200,file=String(at))=>({scenario,score,playedAt:new Date(at).toISOString(),file});
check(m.receive(session,run(first,99999),101000),null,'Old runs rejected');
check(m.receive(session,run('Other',100500),101000),null,'Wrong scenario rejected');
check(m.receive(session,run(session.tracks[1].scenario,100500),101000),null,'Future track cannot complete early');
check(m.receive(session,run(first,900000),101000),null,'Future timestamps rejected');
check(m.receive(session,{scenario:first,score:2,playedAt:null},101000),null,'Missing timestamp rejected');
for(const score of [NaN,Infinity,-1,'100']) check(m.receive(session,run(first,100500,score),101000),null,'Invalid score rejected');
let next=m.receive(session,run(first,100500,0,'file-a'),101000);
check(next.index,1,'Matching run advances once');check(next.tracks[0].score,0,'Zero score retained');check(session.index,0,'Input session immutable');
check(m.receive(next,run(next.tracks[1].scenario,101500,200,'file-a'),102000),null,'Duplicate file rejected');
check(m.valid(JSON.parse(JSON.stringify(next))),true,'JSON persistence roundtrip');
next=m.skip(next,102000);check(next.tracks[1].status,'skipped','Skip is separate from play');
next=m.receive(next,run(next.tracks[2].scenario,102500),103000);
check(next.endedAt,103000,'Last receipt finishes set');check(m.summary(next).played,2,'Skipped track never counts as played');
check(m.summary(next).improved,1,'Comparison uses saved reference');check(m.receive(next,run(first,103500),104000),null,'Finished set ignores receipts');
check(m.valid(next),true,'Recap restorable');
for(const bad of [null,{}, {...session,index:99},{...session,tracks:[]},{...session,armedAt:0},{...session,tracks:[{...session.tracks[0],score:NaN}]}])check(m.valid(bad),false,'Invalid saved data rejected');
console.log(`PASS: ${checks} Mixtape planning, receipt, persistence and recap assertions.`);
