/**
 * Draw the seven new mechanics into assets/brand/mechanics, and hand the renderer its copy.
 *
 *   npm run brand:mechanics     this alone (npm run brand runs it too)
 *
 * Everything comes from src/core/brand/mechanics.ts, the one place a glyph is drawn:
 *
 *   mechanics/icons/<id>.svg                    the 24-unit icon, currentColor: the source
 *   mechanics/icons/{dark,light}/<id>-<px>.png  rasters at 16, 24, 32 and 48 px
 *   mechanics/emblems/{dark,light}/<id>.svg|png the emblem, 320 px, transparent
 *   mechanics/sheet-{dark,light}.svg|png        every icon at its real sizes beside its emblem
 *   src/app/renderer/assets/icons/<id>.svg      the icons, for an <img> or a copy-paste
 *   src/app/renderer/mechanic-icons.js          window.mechanicIcon(id) and mechanicEmblem(id)
 *
 * "Dark" means for a dark ground, as everywhere in the kit: its ink is light.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

import { ICON_ATTRS, MECHANICS, mechanicEmblemSvg, mechanicIconSvg, type MechanicId } from "../../src/core/brand/mechanics.ts";
import { palettes, type BrandPalette } from "../../src/core/brand/palette.ts";
import { placeSvg } from "../../src/core/brand/shareCard.ts";
import { renderChecked } from "./checks.ts";
import { corners, ground, horizontal, stars, svgDoc, t, withFit } from "./draw.ts";
import { ensureDir, root, tokens, withFonts, type RasterJob } from "./kit.ts";

const P = palettes(tokens);
const OUT = join(root, "assets", "brand", "mechanics");
export const ICON_SIZES = [16, 24, 32, 48] as const;

/** The icon in one colour at one pixel size, for a PNG. */
function iconAt(id: MechanicId, ink: string, px: number): string {
  return mechanicIconSvg(id, { size: px, title: MECHANICS.find((m) => m.id === id)?.name }).replace("<svg ", `<svg style="color:${ink}" `);
}

/** The emblem's ink: the brand colour, which is how a mechanic is told from a rank. */
export function emblemInk(p: BrandPalette): string {
  return p.brand;
}

function sheet(p: BrandPalette): string {
  const W = 1600;
  const rowH = 112;
  const top = 168;
  const H = top + MECHANICS.length * rowH + 64;
  const ruleInk = p.theme === "dark" ? "#bad3e9" : p.ink;
  let body = ground(p, W, H, W * 0.92, 0) + stars(p, W, H, 50, 21 + (p.theme === "dark" ? 0 : 1), [[40, 130, W - 80, H - 170]]) + corners(p, W, H, 20, 14);
  body += horizontal(p, 64, 84, 30);
  body += t("New mechanics · icons and emblems", W - 64, 78, { size: 14, fill: p.inkDim, mono: true, anchor: "end", tracking: 0.18, upper: true });
  body += `<path d="M64 112H${W - 64}" stroke="${ruleInk}" stroke-opacity=".2"/>`;
  // Column heads: the icon at each size it is drawn at, then the emblem, then the words.
  const cols = { icons: 80, emblem: 420, name: 560, line: 820 };
  const head = (s: string, x: number) => t(s, x, 146, { size: 11, fill: p.inkDim, mono: true, tracking: 0.18, upper: true });
  body += head("16 · 24 · 32 · 48 px", cols.icons) + head("Emblem", cols.emblem) + head("Name", cols.name) + head("One line", cols.line);
  MECHANICS.forEach((m, i) => {
    const y = top + i * rowH;
    const mid = y + rowH / 2;
    body += `<path d="M64 ${y + rowH}H${W - 64}" stroke="${ruleInk}" stroke-opacity=".1"/>`;
    let x = cols.icons;
    for (const px of ICON_SIZES) {
      body += placeSvg(iconAt(m.id, p.ink, px).replace(/ width="\d+" height="\d+"/, ""), x, Math.round(mid - px / 2), px, px);
      x += px + 34;
    }
    body += placeSvg(mechanicEmblemSvg(m.id, emblemInk(p)), cols.emblem, mid - 44, 88, 88);
    body += t(m.name, cols.name, mid + 9, { size: 26, fill: p.ink, weight: 600 });
    body += t(m.id, cols.name, mid + 34, { size: 12, fill: p.inkDim, mono: true, tracking: 0.08 });
    body += t(m.line, cols.line, mid + 6, { size: 16, fill: p.inkMid, weight: 400, fit: W - 64 - cols.line });
  });
  return svgDoc(W, H, body, "Apogee mechanics: icons and emblems");
}

/**
 * The renderer's copy, as plain script (the renderer has no bundler and no imports).
 * Generated, so the drawing has one home; validate:brand fails if it falls behind.
 */
export function rendererScript(): string {
  const bodies = Object.fromEntries(MECHANICS.map((m) => [m.id, m.icon]));
  const emblems = Object.fromEntries(MECHANICS.map((m) => [m.id, mechanicEmblemSvg(m.id, "currentColor").replace(/^<svg[^>]*>/, "").replace(/<title>[^<]*<\/title>/, "").replace(/<\/svg>$/, "")]));
  const names = Object.fromEntries(MECHANICS.map((m) => [m.id, m.name]));
  const lines = Object.fromEntries(MECHANICS.map((m) => [m.id, m.line]));
  return `/*
 * The new mechanics' icons and emblems, for the renderer.
 * Generated by \`npm run brand:mechanics\` from src/core/brand/mechanics.ts; do not edit.
 *
 *   mechanicIcon("crown")                         decorative 24-unit icon, currentColor
 *   mechanicIcon("crown", { label: "Crown" })     the same, announced to screen readers
 *   mechanicIcon("crown", { className: "nav-icon" })  sized by the rail's own CSS
 *   mechanicEmblem("crown")                       80-unit emblem for an empty state, currentColor
 *   APOGEE_MECHANICS.names.crown, .lines.crown    the name and the one line, as the brand kit has them
 *
 * Ids: shadow, flag, daily, link (challenge link), crown, draft, race (live race).
 */
(function () {
  "use strict";
  var ICON_ATTRS = ${JSON.stringify(ICON_ATTRS)};
  var BODIES = ${JSON.stringify(bodies, null, 2)};
  var EMBLEMS = ${JSON.stringify(emblems, null, 2)};
  var NAMES = ${JSON.stringify(names)};
  var LINES = ${JSON.stringify(lines, null, 2)};
  function esc(s) { return String(s).replace(/[&<>"']/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]; }); }
  function a11y(o) { return o && o.label ? ' role="img" aria-label="' + esc(o.label) + '"><title>' + esc(o.label) + "</title>" : ' aria-hidden="true">'; }
  function cls(o) { return o && o.className ? ' class="' + esc(o.className) + '"' : ""; }
  function size(o) { return o && o.size ? ' width="' + Number(o.size) + '" height="' + Number(o.size) + '"' : ""; }
  function mechanicIcon(id, o) {
    if (!BODIES[id]) throw new Error("no mechanic icon " + id);
    return "<svg" + cls(o) + " " + ICON_ATTRS + size(o) + a11y(o) + BODIES[id] + "</svg>";
  }
  function mechanicEmblem(id, o) {
    if (!EMBLEMS[id]) throw new Error("no mechanic emblem " + id);
    return '<svg' + cls(o) + ' viewBox="0 0 80 80"' + size(o) + a11y(o) + EMBLEMS[id] + "</svg>";
  }
  window.APOGEE_MECHANICS = Object.freeze({ ids: Object.keys(BODIES), names: NAMES, lines: LINES, icon: mechanicIcon, emblem: mechanicEmblem });
  window.mechanicIcon = mechanicIcon;
  window.mechanicEmblem = mechanicEmblem;
})();
`;
}

/** The icon files: one source per id, identical in the kit and in the renderer's assets. */
export function iconFile(id: MechanicId): string {
  return mechanicIconSvg(id, { title: MECHANICS.find((m) => m.id === id)?.name }) + "\n";
}

export const RENDERER_SCRIPT = join(root, "src", "app", "renderer", "mechanic-icons.js");
export const RENDERER_ICONS = join(root, "src", "app", "renderer", "assets", "icons");

/** Write the files that are not rasterised: the icon sources and the renderer's copies. */
export function writeSources(): string[] {
  const written: string[] = [];
  const put = (path: string, data: string) => {
    let before: string | null = null;
    try {
      before = readFileSync(path, "utf8");
    } catch {
      before = null;
    }
    if (before !== data) {
      writeFileSync(ensureDir(path), data);
      written.push(path);
    }
  };
  for (const m of MECHANICS) {
    put(join(OUT, "icons", `${m.id}.svg`), iconFile(m.id));
    put(join(RENDERER_ICONS, `${m.id}.svg`), iconFile(m.id));
  }
  put(RENDERER_SCRIPT, rendererScript());
  return written;
}

export function mechanicJobs(out = OUT): RasterJob[] {
  const jobs: RasterJob[] = [];
  for (const theme of ["dark", "light"] as const) {
    const p = P[theme];
    for (const m of MECHANICS) {
      for (const px of ICON_SIZES) {
        jobs.push({ svg: iconAt(m.id, p.ink, px), pngOut: ensureDir(join(out, "icons", theme, `${m.id}-${px}.png`)), width: px, height: px });
      }
      const base = join(out, "emblems", theme, m.id);
      jobs.push({ svg: mechanicEmblemSvg(m.id, emblemInk(p)), svgOut: ensureDir(`${base}.svg`), pngOut: `${base}.png`, width: 320, height: 320 });
    }
    const s = sheet(p);
    const H = Number(/height="(\d+)"/.exec(s)?.[1]);
    const base = join(out, `sheet-${theme}`);
    jobs.push({ svg: withFit(withFonts(s)), svgOut: ensureDir(`${base}.svg`), pngOut: `${base}.png`, width: 1600, height: H, checks: { inset: 24 } });
  }
  return jobs;
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const written = writeSources();
  console.log(`mechanics: ${written.length} source file(s) changed`);
  const jobs = mechanicJobs();
  console.log(`mechanics: ${jobs.length} images`);
  const r = renderChecked(jobs, "mechanics");
  if (r.failures.length) {
    console.error(r.failures.map((f) => `  FAIL ${f}`).join("\n"));
    process.exit(1);
  }
  console.log(`  ${r.measured} checked for margins, overlap and contrast` + (r.worst ? `; lowest contrast ${r.worst.ratio.toFixed(2)}:1 ("${r.worst.text}")` : ""));
}
